# Generated by Django 3.1.7 on 2021-04-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=70)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlimeTypes',
            fields=[
                ('type_index', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.TextField(default='No color')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slime_behavior.action')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slime_behavior.slimetypes')),
            ],
        ),
    ]
